### ISSUE TITLE
Problem after upgrade to tensorflow 2

### ISSUE THREAD

**Issue by trasse** [mpicbg-csbd/stardist#76]
Dear All,

I just created a new environment to use Stardist with Tensorflow2.
I have in the same environment all dependencies to run Cellpose.
(which works fine for tensorflow 1.12) but not tensorflow 2.0.

All seems fine in the new environment.

import tensorflow as tf
assert tf.test.is_gpu_available()
assert tf.test.is_built_with_cuda()

is fine.

I use:
stardist                  0.6.0 
csbdeep                   0.6.0                    
cudatoolkit            10.0.130                    
cudnn                     7.6.5
mxnet-cu100         1.5.1.post0      
n2v                       0.2.1
tensorflow-gpu            2.0.0
tensorflow                2.0.0
keras                     2.2.5
gcc_linux-64              7.5.0 

Ubuntu 18.04 Cuda 10.0.130

Still stardist does not work.

Do you have any idea why??

 CUDNN_STATUS_INTERNAL_ERROR
2020-07-20 13:37:11.666803: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

Run StarDist SD_2D_dsb2018
Run_SD_ StarDist
Loading network weights from 'weights_last.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.417819, nms_thresh=0.5.
Model_keys dict_keys(['SD_2D_dsb2018'])
Running now:  ['RGBInput_000_leaves_6.tif', 'RGBInput_000_leaves_4.tif']

---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-5-497f0c908306> in <module>
     16 # Segment
     17 start_time = datetime.datetime.now()
---> 18 segment(input_def,pc,run_def,initModelSettings)
     19 end_time = datetime.datetime.now()
     20 time_delta = end_time - start_time

~/github/OpSef_XL/Utils_and_Configs/Segmentation_Func_06.py in segment(input_def, pc, run_def, initModelSettings)
    646             elif run_now == "StarDist":
    647                 results_dic_list.append(run_batch_stardist(run_sub_id,my_model,run_def["ModelType"][run_sub_id], input_def["root"], batch, batch_display, batch_fn,
--> 648                                                            run_def["filter_para"], pc["sub_f"], run_def["run_ID"]))
    649             elif run_now == "Cellprofiler_UNet":
    650                 results_dic_list.append(

~/github/OpSef_XL/Utils_and_Configs/Segmentation_Func_06.py in run_batch_stardist(run_sub_id, mdls, which_model, path, img_batch, img_display, batch_fn_core, obj_filter, sub_folder, runID, rl)
    182         masks = []
    183         for img in img_batch:
--> 184             masks.append(Run_StarDist2D(img[:,:,0].copy(),mdls,which_model))
    185     # save results
    186         for mi,mask in enumerate(masks):

~/github/OpSef_XL/Utils_and_Configs/Segmentation_Func_06.py in Run_StarDist2D(img, mdls, which_model)
     45     im = normalize(img, 1,99.8, axis=axis_norm)
     46     model = mdls[which_model]
---> 47     labels, details = model.predict_instances(im)
     48     return labels
     49 

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/stardist/models/base.py in predict_instances(self, img, axes, normalizer, prob_thresh, nms_thresh, n_tiles, show_tile_progress, verbose, predict_kwargs, nms_kwargs, overlap_label)
    417         _shape_inst   = tuple(s for s,a in zip(_permute_axes(img).shape, _axes_net) if a != 'C')
    418 
--> 419         prob, dist = self.predict(img, axes=axes, normalizer=normalizer, n_tiles=n_tiles, show_tile_progress=show_tile_progress, **predict_kwargs)
    420         return self._instances_from_prediction(_shape_inst, prob, dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh, overlap_label=overlap_label, **nms_kwargs)
    421 

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/stardist/models/base.py in predict(self, img, axes, normalizer, n_tiles, show_tile_progress, **predict_kwargs)
    348 
    349         else:
--> 350             prob, dist = predict_direct(x)
    351 
    352         prob = resizer.after(prob, axes_net)

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/stardist/models/base.py in predict_direct(tile)
    314 
    315         def predict_direct(tile):
--> 316             prob, dist = self.keras_model.predict(tile[np.newaxis], **predict_kwargs)
    317             return prob[0], dist[0]
    318 

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
    907         max_queue_size=max_queue_size,
    908         workers=workers,
--> 909         use_multiprocessing=use_multiprocessing)
    910 
    911   def reset_metrics(self):

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py in predict(self, model, x, batch_size, verbose, steps, callbacks, **kwargs)
    720         verbose=verbose,
    721         steps=steps,
--> 722         callbacks=callbacks)

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py in model_iteration(model, inputs, targets, sample_weights, batch_size, epochs, verbose, callbacks, val_inputs, val_targets, val_sample_weights, shuffle, initial_epoch, steps_per_epoch, validation_steps, validation_freq, mode, validation_in_fit, prepared_feed_values_from_dataset, steps_name, **kwargs)
    391 
    392         # Get outputs.
--> 393         batch_outs = f(ins_batch)
    394         if not isinstance(batch_outs, list):
    395           batch_outs = [batch_outs]

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
   3738         value = math_ops.cast(value, tensor.dtype)
   3739       converted_inputs.append(value)
-> 3740     outputs = self._graph_fn(*converted_inputs)
   3741 
   3742     # EagerTensor.numpy() will often make a copy to ensure memory safety.

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in __call__(self, *args, **kwargs)
   1079       TypeError: For invalid positional/keyword argument combinations.
   1080     """
-> 1081     return self._call_impl(args, kwargs)
   1082 
   1083   def _call_impl(self, args, kwargs, cancellation_manager=None):

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _call_impl(self, args, kwargs, cancellation_manager)
   1119       raise TypeError("Keyword arguments {} unknown. Expected {}.".format(
   1120           list(kwargs.keys()), list(self._arg_keywords)))
-> 1121     return self._call_flat(args, self.captured_inputs, cancellation_manager)
   1122 
   1123   def _filtered_call(self, args, kwargs):

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1222     if executing_eagerly:
   1223       flat_outputs = forward_function.call(
-> 1224           ctx, args, cancellation_manager=cancellation_manager)
   1225     else:
   1226       gradient_name = self._delayed_rewrite_functions.register()

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    509               inputs=args,
    510               attrs=("executor_type", executor_type, "config_proto", config),
--> 511               ctx=ctx)
    512         else:
    513           outputs = execute.execute_with_cancellation(

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     65     else:
     66       message = e.message
---> 67     six.raise_from(core._status_to_exception(e.code, message), None)
     68   except TypeError as e:
     69     keras_symbolic_tensors = [

~/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node down_level_0_no_0/Conv2D (defined at /home/trasse/anaconda3/envs/opsefpy002/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_787]

Function call stack:
keras_scratch_graph

**Comment by maweigert** [comment]
Hi @trasse,

This error typically appears, when cudnn is not found. Did you install it via `conda install cudnn` ?

**Comment by uschmidt83** [comment]
I sometimes get similar errors when there’s not enough GPU memory available for Tensorflow.

**Comment by trasse** [comment]
Dear Martin,

no i did not.
But i just tied.
But it seems it made it worse.
Now Keras find no longer tensorflow and uses the Theano backend.

Kind regards

Tobias

**Comment by maweigert** [comment]
Yeah, installing different cuda/cudnn/tf versions on the same machine is always a bit finicky. Ypu could try to reinstall `tensorflow-gpu` and `keras` after you changed `cudnn`. Maybe that helps.

**Comment by trasse** [comment]
Dear Martin,

Thanks a lot.
What are the exact specifications that work for you?

After a clean new install I end up with:

tensorflow 2.2 and keras 2.43

As I install stardist 

keras is downgraded.

Installing collected packages: keras-applications, keras, csbdeep, stardist
  Attempting uninstall: keras
    Found existing installation: Keras 2.4.3
    Uninstalling Keras-2.4.3:
      Successfully uninstalled Keras-2.4.3
Successfully installed csbdeep-0.6.0 keras-2.3.1 keras-applications-1.0.8 stardist-0.6.0

Things get worse in case i also want n2v that relies also on csb-deep.
ERROR: n2v 0.2.1 has requirement csbdeep<0.6.0,>=0.4.0, but you'll have csbdeep 0.6.0 which is incompatible.
ERROR: n2v 0.2.1 has requirement keras<2.3.0,>=2.2.4, but you'll have keras 2.3.1 which is incompatible.
Installing collected packages: csbdeep
  Attempting uninstall: csbdeep
    Found existing installation: csbdeep 0.5.2
    Uninstalling csbdeep-0.5.2:
      Successfully uninstalled csbdeep-0.5.2

After enforcing csbdeep=0.6.0 keras is still 2.3.1

Next,
conda install --force-reinstall keras=2.4.3

does not help, i get:

keras                     2.2.5
(which no longer recognizes the tensorflow backend....)

Kind regards

Tobias

**Comment by maweigert** [comment]
Yes, n2v has not yet been updated to be compatible with tf 2, so you would need to wait for that to happen (if you want to use everything inside a single conda env).

**Comment by trasse** [comment]
Thanks, 
but even without n2v i get stuck here:

AttributeError: module 'tensorflow' has no attribute 'compat'

tensorflow                2.0.0           gpu_py37h768510d_0  
tensorflow-base           2.0.0           gpu_py37h0ec5d1f_0  
tensorflow-estimator      2.1.0                    pypi_0    pypi
tensorflow-gpu            2.0.0                h0d30ee6_0  

What version of tensorflow did you use for tests?

/github/OpSef_XL/Utils_and_Configs/Segmentation_Func_07_tf20.py in <module>
      7 from csbdeep.utils import Path, normalize
      8 from stardist import random_label_cmap, _draw_polygons
----> 9 from stardist.models import StarDist2D
     10 import tifffile as tif
     11 import pkg_resources

~/anaconda3/envs/op1c/lib/python3.7/site-packages/stardist/models/__init__.py in <module>
      1 from __future__ import absolute_import, print_function
      2 
----> 3 from .model2d import Config2D, StarDist2D, StarDistData2D
      4 from .model3d import Config3D, StarDist3D, StarDistData3D
      5 

~/anaconda3/envs/op1c/lib/python3.7/site-packages/stardist/models/model2d.py in <module>
      6 from tqdm import tqdm
      7 
----> 8 from csbdeep.models import BaseConfig
      9 from csbdeep.internals.blocks import unet_block
     10 from csbdeep.utils import _raise, backend_channels_last, axes_check_and_normalize, axes_dict

~/anaconda3/envs/op1c/lib/python3.7/site-packages/csbdeep/models/__init__.py in <module>
      3 # checks
      4 try:
----> 5     import tensorflow
      6     del tensorflow
      7 except ModuleNotFoundError as e:

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     96 
     97 # We still need all the names that are toplevel on tensorflow_core
---> 98 from tensorflow_core import *
     99 
    100 # These should not be visible in the main tf module.

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_core/__init__.py in <module>
     43 from . _api.v2 import autograph
     44 from . _api.v2 import bitwise
---> 45 from . _api.v2 import compat
     46 from . _api.v2 import config
     47 from . _api.v2 import data

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/__init__.py in <module>
     21 import sys as _sys
     22 
---> 23 from . import v1
     24 from . import v2
     25 from tensorflow.python.compat.compat import forward_compatibility_horizon

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_core/_api/v2/compat/v1/__init__.py in <module>
    662 _current_module = _sys.modules[__name__]
    663 try:
--> 664   from tensorflow_estimator.python.estimator.api._v1 import estimator
    665   _current_module.__path__ = (
    666       [_module_util.get_parent_dir(estimator)] + _current_module.__path__)

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1 import estimator
     11 
     12 del _print_function

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator._api.v1.estimator import experimental
     11 from tensorflow_estimator._api.v1.estimator import export
     12 from tensorflow_estimator._api.v1.estimator import inputs

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
     11 from tensorflow_estimator.python.estimator.canned.kmeans import KMeansClustering as KMeans
     12 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py in <module>
     31 from tensorflow.python.keras.utils import losses_utils
     32 from tensorflow.python.util.tf_export import estimator_export
---> 33 from tensorflow_estimator.python.estimator import estimator
     34 from tensorflow_estimator.python.estimator.canned import head as head_lib
     35 from tensorflow_estimator.python.estimator.canned import optimizers

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/estimator.py in <module>
     51 from tensorflow_estimator.python.estimator import model_fn as model_fn_lib
     52 from tensorflow_estimator.python.estimator import run_config
---> 53 from tensorflow_estimator.python.estimator import util as estimator_util
     54 from tensorflow_estimator.python.estimator.export import export_lib
     55 from tensorflow_estimator.python.estimator.mode_keys import ModeKeys

~/anaconda3/envs/op1c/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/util.py in <module>
     73 
     74 
---> 75 class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
     76   """Creates a SessionRunHook that initializes the passed iterator."""
     77 

AttributeError: module 'tensorflow' has no attribute 'compat'

**Comment by maweigert** [comment]
Hard to tell, as this seems to be a tensorflow issue (can have a lot of reasons, maybe your driver is to old for the cudnn version etc).

**Comment by uschmidt83** [comment]
> After a clean new install I end up with:
> 
> tensorflow 2.2 and keras 2.43
> 
> As I install stardist
> 
> keras is downgraded.

The `keras` package is not used at all by `csbdeep` and `stardist` if you use `tensorflow` 2. (You could even uninstall it.)
However, the `csbdeep` package still requires `keras<2.4.0`, because that's needed if you use it with `tensorflow` 1.
I know that's confusing, but we'd otherwise need different requirements depending on the version of `tensorflow`.

> Things get worse in case i also want n2v that relies also on csb-deep.
> ERROR: n2v 0.2.1 has requirement csbdeep<0.6.0,>=0.4.0, but you'll have csbdeep 0.6.0 which is incompatible.
> ERROR: n2v 0.2.1 has requirement keras<2.3.0,>=2.2.4, but you'll have keras 2.3.1 which is incompatible.

> Yes, n2v has not yet been updated to be compatible with tf 2, so you would need to wait for that to happen (if you want to use everything inside a single conda env).

> but even without n2v i get stuck here:
> 
> AttributeError: module 'tensorflow' has no attribute 'compat'
> 
> tensorflow 2.0.0 gpu_py37h768510d_0
> tensorflow-base 2.0.0 gpu_py37h0ec5d1f_0
> tensorflow-estimator 2.1.0 pypi_0 pypi
> tensorflow-gpu 2.0.0 h0d30ee6_0
> 

As Martin mentioned, you cannot use `n2v` with `tensorflow` 2. At least until they update their package.

> What version of tensorflow did you use for tests?

2.2.0

You can see all details of our tests on Travis and Appveyor:

https://travis-ci.com/github/CSBDeep/CSBDeep
https://ci.appveyor.com/project/UweSchmidt/csbdeep-c2jtk

https://travis-ci.com/github/mpicbg-csbd/stardist
https://ci.appveyor.com/project/UweSchmidt/stardist

**Comment by trasse** [comment]
Dear Uwe,

thanks a lot!
I too tried both 2.2 and 2.0: neither worked for me.

But then i stay with tensorflow 1.12 which works just fine (also with the newest stardist version).
I hope you keep supporting it for a while.

Kind regards

Tobias

**Comment by uschmidt83** [comment]
> But then i stay with tensorflow 1.12 which works just fine (also with the newest stardist version).
> I hope you keep supporting it for a while.

We will support both TensorFlow 1 and 2 as long as it's reasonable.
However, there won't be any further updates for the standalone Keras package and TensorFlow 1.

**Comment by tboo** [comment]
Hi Tobias -

if you are into Docker, the Nvidia Tensorflow container 20.06 works out of the box with TF 2.2 and Stardist. A Dockerfile like this should do:

```
FROM nvcr.io/nvidia/tensorflow:20.06-tf2-py3

RUN git clone https://github.com/mpicbg-csbd/stardist.git && \

        cd stardist/ && \

        pip3 install .

```

All you need is an NVIDIA driver 450+ and Docker 19.03+

**Comment by maweigert** [comment]
Wow, this is cool. Thanks @tboo!

**Comment by trasse** [comment]
@tboo 
Thanks a lot! That is great!

**Comment by tboo** [comment]
> 
> 
> Wow, this is cool. Thanks @tboo!

The only thing that doesn't work is `gpuools` as I struggle to set up an (py)OpenCl environment in this container. So the container above does not fully utilize the GPU. There are a bunch of version conflicts with between TF2/gputools and scipi/numpy
